name: AIBotPlugin
main: com.devone.aibot.AIBotPlugin
version: 1.2
api-version: 1.20
author: DevOne
description: A PaperMC plugin that allows managing AI bots with Citizens NPCs, random skins, and protected zones.

# Ensure Citizens is loaded before this plugin to avoid issues
depend:
  - Citizens 

# Alternatively, use `softdepend` if Citizens is optional
# softdepend:
#   - Citizens

# Ensures plugin loads at the correct time
load: POSTWORLD

commands:

  bot-select:
    description: Selects a bot to receive bot commands.
    usage: /bot-select <bot_name>
    permission: aibotplugin.bot.select

  bot-spawn:
    description: Spawns a bot with a random skin and unique name.
    usage: /bot-spawn
    permission: aibotplugin.bot.spawn

  bot-patrol:
    description: Spawns a bot with a random skin and unique name.
    usage: /bot-patrol
    permission: aibotplugin.bot.patrol

  bot-list:
    description: Lists all active bots.
    usage: /bot-list
    permission: aibotplugin.bot.list

  bot-remove:
    description: Removes a bot by name.
    usage: /bot-remove <bot_name>
    permission: aibotplugin.bot.remove

  bot-remove-all:
    description: Removes all spawned bots.
    usage: /bot-remove-all
    permission: aibotplugin.bot.removeall

  bot-here:
    description: Makes the selected bot approach the player.
    usage: /bot-here
    permission: aibotplugin.bot.here

  bot-stop:
    description: Stops the selected bot from moving.
    usage: /bot-stop
    permission: aibotplugin.bot.stop

  zone-add:
    description: Adds a protected zone at your location.
    usage: /zone-add <radius> <zone_name>
    permission: aibotplugin.zone.add

  zone-remove:
    description: Removes a protected zone.
    usage: /zone-remove <zone_name>
    permission: aibotplugin.zone.remove

  zone-list:
    description: Lists all protected zones.
    usage: /zone-list
    permission: aibotplugin.zone.list